name: colorblast-cli

on:
  push:
    branches:
    - master
    - ci
    paths:
    - ".github/workflows/ci-colorblast-cli.yml"
    - "colorblast-cli/**"
    - "colorblast/**"
    - "any-lexer/**"
    - "text-scanner/**"
    - "Cargo.toml"
  pull_request:
    paths:
    - ".github/workflows/ci-colorblast-cli.yml"
    - "colorblast-cli/**"
    - "colorblast/**"
    - "any-lexer/**"
    - "text-scanner/**"
    - "Cargo.toml"
  schedule:
  - cron: "32 4 * * 5"
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta]
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: -p colorblast-cli --all-targets

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
        exclude:
        - os: macos-latest
          rust: beta
        - os: windows-latest
          rust: beta
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: -p colorblast-cli

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - run: rustup component add rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -p colorblast-cli --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta]
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - run: rustup component add clippy
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -p colorblast-cli -- -D warnings

  # doc:
  #   name: Rustdoc
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #   timeout-minutes: 45
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions-rs/toolchain@v1
  #     with:
  #       profile: minimal
  #       toolchain: nightly
  #       override: true
  #   - uses: actions-rs/cargo@v1
  #     with:
  #       command: rustdoc
  #       args: -p colorblast-cli -- -Z unstable-options --check --deny rustdoc::all
